#------------------------------------------------------------------------------
# Makefile.static
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

# Target for the executable
all:

install:
	install -d $(PREFIX)/bin
	install -m 755 do_snow_cover.py $(PREFIX)/bin

clean:

